#cloud-config

coreos:
  etcd:
    addr: "172.16.1.20:4001"
    discovery: "https://discovery.etcd.io/7743a539914ed6a8a2a814f958348291"
    name: coreos0
    peer-addr: "172.16.1.20:7001"
  units:
    - command: start
      name: etcd.service
    - command: start
      name: fleet.service
hostname: coreos0
ssh_authorized_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNQYI1x21AkfX4T9WynkXyP36Hf7NWjAPlgoQByWHA4O6XiXitHTeCgZsPPKqQaNdYU7Dq3mX3sg24IU8X5j2WY/vMDTOMiBaebSOulZDULfpHI+RSb9iczWmzRngh4DbCwEZZU999HaQ2VcGqO4juul5hUW+fdQZvzqOL2J0Jj833AiYoQssOVIdPxGkEZejncCat/A6PpwLKh6p/Yq8fC/1YbJLAcTeWJmCDIU9oY6K1MEiNkcibwRTkr/khKI0fAPWuJBkW5D12JJWfT14aHqVL3I8Ypk4b3dZb+wH/RCd2nJpEy22coFLvUnQgoLmfiDOtUASdSJAE5Wcpet4p"

# Add users to the system. Users are added after groups are added.
users:
  - name: administrator
    gecos: local root user for
    passwd: $6$rounds=4096$MxDohXMh$fUmSID8NvGFi8Pb1eH.5YEWlXGub4KVpXszu6GrYmNaQ246Y/y8HSvXJ46ktlQ.xkC2YrZJfmBJxtDCd7Cuds.
    no-create-home: true
    groups:
      - sudo
      - docker
    no-user-group: true
    system: true

write_files:
    - path: /etc/environment
      permissions: 0644
      content: |
        COREOS_PUBLIC_IPV4=172.16.1.20
        COREOS_PRIVATE_IPV4=172.16.1.20
    - path: /etc/profile.d/alias.sh
      content: |
        alias d='docker'
        alias ds='docker ps'
        alias di='docker images'
        alias drm='docker rm -f $(docker ps -qa)'
        alias k='kubecfg'
        alias kc='kubecfg -c'
        alias sd='sudo systemctl'
        alias cci='sudo coreos-cloudinit --from-file'
        alias j='journalctl'
        alias f='fleetctl'


